import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { authorizeDailyLock, createDailyGlobalLock, pairedPreview, previewFingerprint, readDailyGlobalLock, signPreview, type DailyLockStore } from "./daily-global-lock";
import type { DailyGlobalModeResult } from "./analysis/daily-global-targets";

const oldSecret=process.env.DAILY_LOCK_SECRET;
beforeEach(()=>{process.env.DAILY_LOCK_SECRET="test-lock-secret";delete process.env.DAILY_LOCK_SIGNING_SECRET});
afterEach(()=>{if(oldSecret)process.env.DAILY_LOCK_SECRET=oldSecret;else delete process.env.DAILY_LOCK_SECRET});

function mode(digits:string[],id:string):DailyGlobalModeResult{return{mode:id==="a"?"locked":"today_eligible",configuredCount:1,eligibleCount:1,contributorIds:[id],eligibility:[],result:{rankedDigits:digits.map((digit,index)=>({digit,score:10-index})),digits:digits.slice(0,6).map((digit,index)=>({digit,score:10-index})),sufficient:true} as DailyGlobalModeResult["result"]}}
function preview(){return pairedPreview({targetDate:"2026-09-12",weekday:6,plan:{deadlineBangkok:"2099-09-12T05:40:00+07:00",firstResultAt:"05:45",exactDeadlineKnown:true,reason:"earliest-confirmed-close"},targets:[{lotteryId:"target",name:"Target",resultAt:"05:45",closeAt:"05:40",resultStartMinutes:345,historicalEvaluationEligible:true,scheduleIssues:[]}],a:mode(["0","1","2","3","4","5"],"a"),b:mode(["9","8","7","6","5","4"],"b"),versions:{a:"ha",b:"hb"}})}
function memoryStore(){let row:Record<string,unknown>|null=null;const store:DailyLockStore={read:async()=>row as never,insertBeforeDeadline:async(value)=>{await Promise.resolve();if(row)return null;row={...value,created_at:"2026-09-11T20:00:00.000Z"};return row as never}};return{store,get:()=>row}}

describe("paired daily lock",()=>{
  it("fails closed when lock authorization is not configured",()=>{delete process.env.DAILY_LOCK_SECRET;expect(authorizeDailyLock(new Request("http://localhost/api",{method:"POST"}))).toMatchObject({ok:false,status:503})});
  it("requires a real configured secret",()=>{expect(authorizeDailyLock(new Request("http://localhost/api",{method:"POST"}))).toMatchObject({ok:false,status:401});expect(authorizeDailyLock(new Request("http://localhost/api",{method:"POST",headers:{"x-daily-lock-secret":"bad"}}))).toMatchObject({ok:false,status:403});expect(authorizeDailyLock(new Request("http://localhost/api",{method:"POST",headers:{"x-daily-lock-secret":"test-lock-secret"}}))).toEqual({ok:true})});
  it("atomically stores A and B in one immutable row",async()=>{const p=preview(),m=memoryStore(),fingerprint=previewFingerprint(p),result=await createDailyGlobalLock({preview:p,previewFingerprint:fingerprint,previewSignature:signPreview(fingerprint)!,store:m.store,now:new Date("2026-09-11T00:00:00Z")});expect(result.created).toBe(true);expect(result.record.modes.a.digits).toEqual(["0","1","2","3","4","5"]);expect(result.record.modes.b.digits).toEqual(["9","8","7","6","5","4"]);expect(m.get()).not.toBeNull()});
  it("is idempotent and concurrent requests return the one persisted record",async()=>{const p=preview(),m=memoryStore(),fingerprint=previewFingerprint(p),input={preview:p,previewFingerprint:fingerprint,previewSignature:signPreview(fingerprint)!,store:m.store,now:new Date("2026-09-11T00:00:00Z")};const [x,y]=await Promise.all([createDailyGlobalLock(input),createDailyGlobalLock(input)]);expect([x.created,y.created].filter(Boolean)).toHaveLength(1);expect(x.record.id).toBe(y.record.id)});
  it("rejects stale or substituted previews",async()=>{const p=preview(),m=memoryStore();await expect(createDailyGlobalLock({preview:p,previewFingerprint:"stale",previewSignature:"stale",store:m.store})).rejects.toThrow("preview-mismatch")});
  it("rejects creation at or after the server deadline",async()=>{const p=preview();p.deadlineBangkok="2026-09-12T05:40:00+07:00";const m=memoryStore(),fingerprint=previewFingerprint(p);await expect(createDailyGlobalLock({preview:p,previewFingerprint:fingerprint,previewSignature:signPreview(fingerprint)!,store:m.store,now:new Date("2026-09-11T22:40:00Z")})).rejects.toThrow("lock-deadline-passed")});
  it("keeps reading the persisted digits after a later preview changes",async()=>{const p=preview(),m=memoryStore(),fingerprint=previewFingerprint(p);await createDailyGlobalLock({preview:p,previewFingerprint:fingerprint,previewSignature:signPreview(fingerprint)!,store:m.store,now:new Date("2026-09-11T00:00:00Z")});p.modes.a.digits=["9","8","7","6","5","4"];expect((await readDailyGlobalLock(p.targetDate,m.store))?.modes.a.digits).toEqual(["0","1","2","3","4","5"])});
});
