import type { AlgorithmDefinition } from "./types";
export const CORE_CANDIDATES: readonly AlgorithmDefinition[] = Object.freeze([
  {
    id: "core-candidate-a",
    name: "Candidate A — Balanced Refined",
    version: "1.0.0",
    description: "Reduce sparse pair evidence and emphasize digit marginals",
    digitWeights: {
      frequency: 0.35,
      recentFrequency: 0.25,
      momentum: 0.1,
      positionStrength: 0.2,
      gapPattern: 0.1,
    },
    pairWeights: {
      digitA: 0.35,
      digitB: 0.35,
      pairFrequency: 0.05,
      recentPairTrend: 0.05,
      positionMatch: 0.2,
    },
  },
  {
    id: "core-candidate-b",
    name: "Candidate B — Recent + Position",
    version: "1.0.0",
    description: "Emphasize recent digit strength and positional compatibility",
    digitWeights: {
      frequency: 0.15,
      recentFrequency: 0.4,
      momentum: 0.1,
      positionStrength: 0.3,
      gapPattern: 0.05,
    },
    pairWeights: {
      digitA: 0.25,
      digitB: 0.25,
      pairFrequency: 0.05,
      recentPairTrend: 0.1,
      positionMatch: 0.35,
    },
  },
  {
    id: "core-candidate-c",
    name: "Candidate C — Stable Digit First",
    version: "1.0.0",
    description: "Use digit marginals as the dominant pair signal",
    digitWeights: {
      frequency: 0.4,
      recentFrequency: 0.2,
      momentum: 0.05,
      positionStrength: 0.3,
      gapPattern: 0.05,
    },
    pairWeights: {
      digitA: 0.4,
      digitB: 0.4,
      pairFrequency: 0.05,
      recentPairTrend: 0,
      positionMatch: 0.15,
    },
  },
  {
    id: "core-candidate-d",
    name: "Candidate D — Position Stable",
    version: "1.0.0",
    description: "Remove momentum and reduce sparse pair evidence",
    digitWeights: {
      frequency: 0.45,
      recentFrequency: 0.15,
      momentum: 0,
      positionStrength: 0.35,
      gapPattern: 0.05,
    },
    pairWeights: {
      digitA: 0.3,
      digitB: 0.3,
      pairFrequency: 0.05,
      recentPairTrend: 0,
      positionMatch: 0.35,
    },
  },
  {
    id: "core-candidate-e",
    name: "Candidate E — Long Horizon",
    version: "1.0.0",
    description: "Favor long-run frequency and position signals",
    digitWeights: {
      frequency: 0.5,
      recentFrequency: 0.1,
      momentum: 0,
      positionStrength: 0.35,
      gapPattern: 0.05,
    },
    pairWeights: {
      digitA: 0.35,
      digitB: 0.35,
      pairFrequency: 0.05,
      recentPairTrend: 0,
      positionMatch: 0.25,
    },
  },
] as const);
