import type { LotteryDraw } from "../types";import type { Side } from "./types";import { countDigit,gapStats,momentum,positionFrequency } from "./engine";
export type PairModelId="current"|"digit-only"|"pair-frequency"|"recent-pair"|"position-only"|"digit-position"|"digit-pair"|"digit-position-pair"|"pair-v2-digit-first"|"pair-v3-position-first"|"pair-v4-smoothed";
export const PAIR_MODELS:{id:PairModelId;name:string;experimental?:boolean}[]=[{id:"current",name:"Current Pair"},{id:"digit-only",name:"Digit Strength only"},{id:"pair-frequency",name:"Pair Frequency only"},{id:"recent-pair",name:"Recent Pair only"},{id:"position-only",name:"Position only"},{id:"digit-position",name:"Digit + Position"},{id:"digit-pair",name:"Digit + Pair Frequency"},{id:"digit-position-pair",name:"Digit + Position + Pair"},{id:"pair-v2-digit-first",name:"Pair v2 — Digit First",experimental:true},{id:"pair-v3-position-first",name:"Pair v3 — Position First",experimental:true},{id:"pair-v4-smoothed",name:"Pair v4 — Smoothed Pair",experimental:true}];
type Components={digitA:number;digitB:number;exact:number;recent:number;position:number;unordered:number};export type RankedPair={pair:string;score:number;components:Components};
const clamp=(n:number)=>Math.max(0,Math.min(100,n)),round=(n:number)=>Math.round(n*10)/10,field=(d:LotteryDraw,s:Side)=>s==="top"?d.top2:d.bottom2;
function normalize(values:number[]){const max=Math.max(...values,1);return values.map(x=>x/max*100)}
function digitScores(draws:LotteryDraw[],side:Side){const raw=Array.from({length:10},(_,i)=>{const digit=String(i),mom=momentum(draws,digit,side),pos=positionFrequency(draws,side,digit),gap=gapStats(draws,digit,side);return{digit,freq:countDigit(draws,digit,side),recent:mom.recent,mom:mom.value,pos:Math.max(...Object.values(pos)),gap:gap.gap}}),freq=normalize(raw.map(x=>x.freq)),recent=normalize(raw.map(x=>x.recent)),pos=normalize(raw.map(x=>x.pos));return raw.map((x,i)=>({digit:x.digit,score:round(freq[i]*.3+recent[i]*.25+clamp(50+x.mom*12.5)*.2+pos[i]*.15+(x.gap===null?0:clamp(100-x.gap*12))*.1)})).sort((a,b)=>b.score-a.score||a.digit.localeCompare(b.digit))}
function weights(id:PairModelId,c:Components){switch(id){case"digit-only":return(c.digitA+c.digitB)/2;case"pair-frequency":return c.exact;case"recent-pair":return c.recent;case"position-only":return c.position;case"digit-position":return(c.digitA+c.digitB)*.3+c.position*.4;case"digit-pair":return(c.digitA+c.digitB)*.25+c.exact*.5;case"digit-position-pair":return(c.digitA+c.digitB)*.2+c.position*.3+c.exact*.3;case"pair-v2-digit-first":return(c.digitA+c.digitB)*.35+c.exact*.1+c.recent*.05+c.position*.15;case"pair-v3-position-first":return(c.digitA+c.digitB)*.2+c.exact*.1+c.recent*.05+c.position*.45;case"pair-v4-smoothed":return(c.digitA+c.digitB)*.2+c.exact*.15+c.recent*.05+c.position*.25+c.unordered*.15;default:return c.digitA*.25+c.digitB*.25+c.exact*.2+c.recent*.15+c.position*.15}}
export function rankPairsForModel(draws:LotteryDraw[],side:Side,modelId:PairModelId):RankedPair[]{const digits=digitScores(draws,side),digitMap=new Map(digits.map(x=>[x.digit,x.score])),pairs=Array.from({length:100},(_,i)=>String(i).padStart(2,"0")),exactRaw=pairs.map(p=>draws.filter(d=>field(d,side)===p).length),recentRaw=pairs.map(p=>draws.slice(0,10).filter(d=>field(d,side)===p).length),unorderedRaw=pairs.map(p=>draws.filter(d=>{const v=field(d,side);return v&&[...v].sort().join("")===[...p].sort().join("")}).length),exact=normalize(exactRaw),recent=normalize(recentRaw),unordered=normalize(unorderedRaw),tens=Array.from({length:10},(_,i)=>positionFrequency(draws,side,String(i)).tens),units=Array.from({length:10},(_,i)=>positionFrequency(draws,side,String(i)).units),tensN=normalize(tens),unitsN=normalize(units),maxPos=normalize(Array.from({length:10},(_,i)=>Math.max(...Object.values(positionFrequency(draws,side,String(i))))));return pairs.map((pair,i)=>{const oriented=(tensN[Number(pair[0])]+unitsN[Number(pair[1])])/2,currentPosition=(maxPos[Number(pair[0])]+maxPos[Number(pair[1])])/2,components={digitA:digitMap.get(pair[0])??0,digitB:digitMap.get(pair[1])??0,exact:exact[i],recent:recent[i],position:modelId==="current"?currentPosition:oriented,unordered:unordered[i]};return{pair,components,score:round(weights(modelId,components))}}).sort((a,b)=>b.score-a.score||a.pair.localeCompare(b.pair))}
export type PairDiagnosticRow={drawDate:string;side:Side;actual:string;actualRank:number;digitARank:number;digitBRank:number;pairFrequencyRank:number;recentPairRank:number;positionScore:number;components:Components;uniqueObserved:number;unseenPercent:number;medianFrequency:number};
function rankOf(values:{pair:string;score:number}[],pair:string){return values.findIndex(x=>x.pair===pair)+1}
export function walkForwardPairDiagnostics(history:LotteryDraw[],side:Side,window=30,testDraws=30,modelId:PairModelId="current"){const chronological=[...history].sort((a,b)=>a.drawDate.localeCompare(b.drawDate)),rows:PairDiagnosticRow[]=[];for(let i=window;i<chronological.length;i++){const training=chronological.slice(i-window,i).reverse(),actual=field(chronological[i],side);if(!actual)continue;const ranked=rankPairsForModel(training,side,modelId),digits=digitScores(training,side),exact=ranked.map(x=>({pair:x.pair,score:training.filter(d=>field(d,side)===x.pair).length})).sort((a,b)=>b.score-a.score||a.pair.localeCompare(b.pair)),recent=ranked.map(x=>({pair:x.pair,score:training.slice(0,10).filter(d=>field(d,side)===x.pair).length})).sort((a,b)=>b.score-a.score||a.pair.localeCompare(b.pair)),actualEntry=ranked.find(x=>x.pair===actual)!,frequencies=Array.from({length:100},(_,n)=>training.filter(d=>field(d,side)===String(n).padStart(2,"0")).length).sort((a,b)=>a-b),uniqueObserved=new Set(training.map(d=>field(d,side)).filter(Boolean)).size;rows.push({drawDate:chronological[i].drawDate,side,actual,actualRank:rankOf(ranked,actual),digitARank:digits.findIndex(x=>x.digit===actual[0])+1,digitBRank:digits.findIndex(x=>x.digit===actual[1])+1,pairFrequencyRank:rankOf(exact,actual),recentPairRank:rankOf(recent,actual),positionScore:actualEntry.components.position,components:actualEntry.components,uniqueObserved,unseenPercent:100-uniqueObserved,medianFrequency:(frequencies[49]+frequencies[50])/2})}return rows.slice(-testDraws)}
export function summarizePairDiagnostics(rows:PairDiagnosticRow[]){const ranks=rows.map(x=>x.actualRank).sort((a,b)=>a-b),mean=rows.length?rows.reduce((n,x)=>n+x.actualRank,0)/rows.length:0,inside=(n:number)=>rows.filter(x=>x.actualRank<=n).length;return{sampleSize:rows.length,medianRank:ranks.length?ranks[Math.floor(ranks.length/2)]:0,meanRank:round(mean),top1:inside(1),top4:inside(4),top10:inside(10),top20:inside(20),top50:inside(50),averageUnique:round(rows.reduce((n,x)=>n+x.uniqueObserved,0)/(rows.length||1)),averageUnseenPercent:round(rows.reduce((n,x)=>n+x.unseenPercent,0)/(rows.length||1)),medianPairFrequency:rows.length?rows.map(x=>x.medianFrequency).sort((a,b)=>a-b)[Math.floor(rows.length/2)]:0}}
