import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { createDailyGlobalLock, pairedPreview, previewFingerprint, readDailyGlobalLock, signPreview, type DailyLockStore } from "../src/lib/daily-global-lock";
import type { DailyGlobalModeResult } from "../src/lib/analysis/daily-global-targets";

const run=promisify(execFile),url=process.env.TEST_DATABASE_URL,psql=process.env.PSQL_PATH;
if(!url||!psql)throw new Error("TEST_DATABASE_URL and PSQL_PATH are required");
if(process.env.DATABASE_URL&&url===process.env.DATABASE_URL)throw new Error("Refusing to use DATABASE_URL as the disposable test database");
if(!/localhost|127\.0\.0\.1/.test(url)&&process.env.ALLOW_REMOTE_DISPOSABLE_TEST_DATABASE!=="true")throw new Error("Remote TEST_DATABASE_URL requires ALLOW_REMOTE_DISPOSABLE_TEST_DATABASE=true");
process.env.DAILY_LOCK_SECRET="acceptance-only-secret";
const literal=(value:unknown)=>`'${String(value).replaceAll("'","''")}'`,query=async(sql:string)=>{const {stdout}=await run(psql,["-X","-qAt","-v","ON_ERROR_STOP=1","-d",url,"-c",sql],{windowsHide:true,maxBuffer:1024*1024});return stdout.trim()},json=(value:unknown)=>literal(JSON.stringify(value));

await query(`DROP TABLE IF EXISTS global_prediction_snapshots; CREATE TABLE global_prediction_snapshots(id uuid PRIMARY KEY,target_date date NOT NULL,weekday smallint NOT NULL CHECK(weekday BETWEEN 0 AND 6),formula_version text NOT NULL,history_version text NOT NULL,ranked_digits jsonb NOT NULL CHECK(ranked_digits ? 'a' AND ranked_digits ? 'b'),source_lottery_ids jsonb NOT NULL CHECK(source_lottery_ids ? 'a' AND source_lottery_ids ? 'b'),analysis_options jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(target_date,formula_version)); CREATE OR REPLACE FUNCTION reject_lock_mutation() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'immutable';END$$; CREATE TRIGGER lock_immutable BEFORE UPDATE OR DELETE ON global_prediction_snapshots FOR EACH ROW EXECUTE FUNCTION reject_lock_mutation();`);

const store:DailyLockStore={
  async read(targetDate,formulaVersion){const out=await query(`SELECT row_to_json(x) FROM (SELECT * FROM global_prediction_snapshots WHERE target_date=${literal(targetDate)}::date AND formula_version=${literal(formulaVersion)} LIMIT 1)x`);return out?JSON.parse(out):null},
  async insertBeforeDeadline(row,deadline){const out=await query(`WITH inserted AS (INSERT INTO global_prediction_snapshots(id,target_date,weekday,formula_version,history_version,ranked_digits,source_lottery_ids,analysis_options) SELECT ${literal(row.id)}::uuid,${literal(row.target_date)}::date,${row.weekday},${literal(row.formula_version)},${literal(row.history_version)},${json(row.ranked_digits)}::jsonb,${json(row.source_lottery_ids)}::jsonb,${json(row.analysis_options)}::jsonb WHERE now()<${literal(deadline)}::timestamptz ON CONFLICT(target_date,formula_version)DO NOTHING RETURNING *)SELECT row_to_json(inserted) FROM inserted`);return out?JSON.parse(out):null},
};
const mode=(id:string,digits:string[]):DailyGlobalModeResult=>({mode:id==="a"?"locked":"today_eligible",configuredCount:2,eligibleCount:1,contributorIds:[id],eligibility:[],result:{sufficient:true,rankedDigits:digits.map((digit,index)=>({digit,score:10-index})),digits:digits.slice(0,6).map((digit,index)=>({digit,score:10-index}))} as DailyGlobalModeResult["result"]}),
  makePreview=(date:string,deadline:string)=>pairedPreview({targetDate:date,weekday:1,plan:{deadlineBangkok:deadline,firstResultAt:"05:45",exactDeadlineKnown:true,reason:"earliest-confirmed-close"},targets:[{lotteryId:"target",name:"target",resultAt:"05:45",closeAt:"05:40",resultStartMinutes:345,historicalEvaluationEligible:true,scheduleIssues:[]}],a:mode("a",["0","1","2","3","4","5"]),b:mode("b",["9","8","7","6","5","4"]),versions:{a:"a-v1",b:"b-v1"}}),
  lock=(preview:ReturnType<typeof makePreview>)=>{const fingerprint=previewFingerprint(preview);return createDailyGlobalLock({preview,previewFingerprint:fingerprint,previewSignature:signPreview(fingerprint)!,store})};

const firstPreview=makePreview("2099-01-01","2099-01-01T05:40:00+07:00"),first=await lock(firstPreview),retry=await lock(firstPreview);
if(!first.created||retry.created||first.record.id!==retry.record.id)throw new Error("create/retry acceptance failed");
const changed=makePreview("2099-01-01","2099-01-01T05:40:00+07:00");changed.modes.a.digits=["9","8","7","6","5","4"];const afterSourceChange=await lock(changed);if(afterSourceChange.record.id!==first.record.id||afterSourceChange.record.modes.a.digits.join("")!=="012345")throw new Error("source-change immutability acceptance failed");
const concurrentPreview=makePreview("2099-01-02","2099-01-02T05:40:00+07:00"),concurrent=await Promise.all([lock(concurrentPreview),lock(concurrentPreview)]);
if(concurrent.filter(x=>x.created).length!==1||new Set(concurrent.map(x=>x.record.id)).size!==1)throw new Error("concurrency acceptance failed");
const expired=makePreview("2020-01-01","2020-01-01T05:40:00+07:00");let expiredRejected=false;try{await lock(expired)}catch(error){expiredRejected=String(error).includes("lock-deadline-passed")}if(!expiredRejected||await readDailyGlobalLock("2020-01-01",store))throw new Error("deadline/no-partial acceptance failed");
if((await readDailyGlobalLock("2099-01-01",store))?.id!==first.record.id)throw new Error("post-deadline read acceptance failed");
const restart=await run(process.execPath,["node_modules/tsx/dist/cli.mjs","scripts/read-daily-global-lock-postgres.mts","2099-01-01"],{cwd:process.cwd(),windowsHide:true,env:{...process.env,TEST_DATABASE_URL:url,PSQL_PATH:psql}}),restartRecord=JSON.parse(restart.stdout.trim());if(restartRecord.id!==first.record.id||restartRecord.a.join("")!=="012345")throw new Error("process-restart persistence acceptance failed");
const badId="00000000-0000-4000-8000-000000000099";let statementFailed=false;try{await query(`INSERT INTO global_prediction_snapshots(id,target_date,weekday,formula_version,history_version,ranked_digits,source_lottery_ids,analysis_options)VALUES(${literal(badId)}::uuid,'2099-01-03',1,'broken','h','{}','{}','{}')`)}catch{statementFailed=true}if(!statementFailed||await query(`SELECT count(*) FROM global_prediction_snapshots WHERE id=${literal(badId)}::uuid`)!=="0")throw new Error("failed-write atomicity acceptance failed");
console.log(JSON.stringify({database:"disposable TEST_DATABASE_URL",transport:"psql adapter through DailyLockStore boundary",createAtomic:first.record.modes.a.digits.length===6&&first.record.modes.b.digits.length===6,retrySameRecord:retry.record.id===first.record.id,concurrentSingleRecord:new Set(concurrent.map(x=>x.record.id)).size===1,deadlineRejected:expiredRejected,readAfterDeadline:true,sourceChangeKeptOriginal:true,processRestartKeptOriginal:true,failedWriteNoPartial:true,recordId:first.record.id},null,2));
