import { promises as fs } from "node:fs";import path from "node:path";
import { buildDailyGlobalComparison,targetOutcomePopulation } from "../src/lib/analysis/daily-global-targets";import { drawWeekday } from "../src/lib/analysis/day-pattern";import type { PlayedUniverseWeekday } from "../src/lib/analysis/played-universe";import type { Snapshot } from "../src/lib/cache";import type { LotteryDefinition } from "../src/lib/types";
const root=process.cwd(),catalog=JSON.parse(await fs.readFile(path.join(root,"data/lotteries.json"),"utf8")) as LotteryDefinition[],files=(await fs.readdir(path.join(root,"data/history"))).filter(x=>x.endsWith(".json")),snapshots:Record<string,Snapshot>={};for(const file of files){const x=JSON.parse(await fs.readFile(path.join(root,"data/history",file),"utf8")) as Snapshot;snapshots[x.lotteryId]=x}
type Item={date:string;weekday:number;lotteryId:string;name:string;resultAt:string;timeBand:string};
const dates=[...new Set(Object.values(snapshots).flatMap(x=>x.draws.map(d=>d.drawDate)))].filter(x=>x<="2026-09-11").sort(),opportunities:Item[]=[],missing:Array<Item&{reason:"no-target-date-result"|"incomplete-target-date-result"}>=[],uncertain:Record<string,{name:string;days:number;issues:string[]}>= {},evaluatedDays:string[]=[];let expected=0,available=0;
const band=(time:string)=>{const h=Number(time.slice(0,2));return h<5?"date-boundary-unverified":h<12?"05:00-11:59":h<17?"12:00-16:59":h<22?"17:00-21:59":"22:00-23:59"};
for(const date of dates){const weekday=drawWeekday(date) as PlayedUniverseWeekday,c=buildDailyGlobalComparison({catalog,snapshots,targetDate:date,weekday,historical:true}),p=targetOutcomePopulation(c,snapshots);if(!p.available.length||!c.modes.locked.result.sufficient||!c.modes.today_eligible.result.sufficient)continue;evaluatedDays.push(date);expected+=p.scheduled;available+=p.available.length;for(const target of c.targets.filter(x=>x.historicalEvaluationEligible)){const item={date,weekday,lotteryId:target.lotteryId,name:target.name,resultAt:target.resultAt,timeBand:band(target.resultAt)};opportunities.push(item);const draws=(snapshots[target.lotteryId]?.draws??[]).filter(x=>x.drawDate===date);if(!draws.some(x=>x.top2&&x.bottom2))missing.push({...item,reason:draws.length?"incomplete-target-date-result":"no-target-date-result"})}for(const target of c.scheduleLimitations){const x=uncertain[target.lotteryId]??={name:target.name,days:0,issues:target.scheduleIssues};x.days++}}
const group=<T extends string>(key:(x:Item)=>T)=>{const out:Record<string,{key:T;expected:number;missing:number;rate:number}>={};for(const x of opportunities){const k=key(x);out[k]??={key:k,expected:0,missing:0,rate:0};out[k].expected++}for(const x of missing){const k=key(x);out[k].missing++}for(const x of Object.values(out))x.rate=x.missing/x.expected;return Object.values(out)};
const byLottery=group(x=>x.lotteryId).map(x=>({...x,lotteryId:x.key,name:catalog.find(l=>l.id===x.key)?.name??x.key})).sort((a,b)=>b.missing-a.missing);
const reasonCounts=(["no-target-date-result","incomplete-target-date-result"] as const).map(reason=>{const count=missing.filter(x=>x.reason===reason).length;return{reason,expected,missing:count,rate:count/expected}});
console.log(JSON.stringify({scope:{evaluatedDays:evaluatedDays.length,endDate:"2026-09-11",expected,available,missing:missing.length,missingRate:missing.length/expected},reasons:reasonCounts,byWeekday:group(x=>String(x.weekday)),byDate:group(x=>x.date).sort((a,b)=>b.missing-a.missing),byTimeBand:group(x=>x.timeBand),byLottery,uncertainScheduleDateBoundary:Object.entries(uncertain).map(([lotteryId,x])=>({lotteryId,...x})),notes:["Expected counts include only historically evaluable explicit schedules on the 97 paired comparison days.","Uncertain post-midnight date boundaries are reported separately and are not part of the 550.","No missing value was imputed or relabeled as a win/loss."]},null,2));
