import { promises as fs } from "node:fs";
import path from "node:path";
import { readAllSnapshots } from "../src/lib/cache";
import { duplicateGroups, type GlobalWeekdaySource } from "../src/lib/analysis/global-weekday-evaluation";

const snapshots = Object.values(await readAllSnapshots()), sources: GlobalWeekdaySource[] = snapshots.map((item) => ({ lotteryId: item.lotteryId, draws: item.draws }));
const pairs: { left:string; right:string; overlap:number; exactFullRate:number; topRate:number; bottomRate:number }[] = [];
for (let i=0;i<sources.length;i+=1) for (let j=i+1;j<sources.length;j+=1) { const a=new Map(sources[i].draws.filter(d=>d.top2&&d.bottom2).map(d=>[d.drawDate,d])), aligned=sources[j].draws.filter(d=>a.has(d.drawDate)&&d.top2&&d.bottom2); if(aligned.length<10)continue; const exact=aligned.filter(d=>{const x=a.get(d.drawDate)!;return x.top2===d.top2&&x.bottom2===d.bottom2}).length, top=aligned.filter(d=>a.get(d.drawDate)!.top2===d.top2).length,bottom=aligned.filter(d=>a.get(d.drawDate)!.bottom2===d.bottom2).length; pairs.push({left:sources[i].lotteryId,right:sources[j].lotteryId,overlap:aligned.length,exactFullRate:exact/aligned.length,topRate:top/aligned.length,bottomRate:bottom/aligned.length}); }
const groups=duplicateGroups(sources,"9999-12-31").filter(group=>group.length>1), report={generatedAt:new Date().toISOString(),thresholds:{minimumOverlap:10,exactFullRate:0.8},lotteryCount:sources.length,comparablePairCount:pairs.length,duplicateGroups:groups,strongestPairs:pairs.sort((a,b)=>b.exactFullRate-a.exactFullRate||b.overlap-a.overlap).slice(0,30)};
await fs.mkdir(path.join(process.cwd(),"reports"),{recursive:true}); await fs.writeFile(path.join(process.cwd(),"reports/global-lottery-correlation-audit.json"),JSON.stringify(report,null,2)); await fs.writeFile(path.join(process.cwd(),"reports/global-lottery-correlation-audit.md"),`# Global lottery duplicate audit\n\nGenerated: ${report.generatedAt}\n\n- Lotteries: ${report.lotteryCount}\n- Comparable pairs: ${report.comparablePairCount}\n- Duplicate threshold: exact top2+bottom2 >= 80% on >= 10 aligned dates\n- Duplicate groups: ${groups.length}\n\n${groups.length?groups.map(g=>`- ${g.join(", ")}`).join("\n"):"No duplicate groups passed the frozen threshold."}\n\nThis is a dependency audit, not predictive evidence.\n`); console.log(JSON.stringify(report,null,2));
