import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import nextEnv from "@next/env";
import { readAllSnapshots } from "../src/lib/cache";
import { getCanonicalDataset } from "../src/lib/history-provider";
import { drawWeekday } from "../src/lib/analysis/day-pattern";
import { eligibleGlobalWeekdaySources, exactRandomBothCoverage, exactRandomPairCoverage, pairCovered, rankGlobalWeekdayMethod, type GlobalWeekdaySource } from "../src/lib/analysis/global-weekday-evaluation";
import { rankTemporalShrinkage, type TemporalShrinkageOptions } from "../src/lib/analysis/global-temporal-shrinkage";

const FREEZE_DATE = "2026-09-11", SIZE = 6, BOOTSTRAPS = 10000, SEED = 20260911,
  HALF_LIVES: TemporalShrinkageOptions["halfLife"][] = [2, 4, 8, "flat"],
  PRIOR_STRENGTHS: TemporalShrinkageOptions["priorStrength"][] = [2, 6, 12],
  candidates = HALF_LIVES.flatMap((halfLife) => PRIOR_STRENGTHS.map((priorStrength) => ({ halfLife, priorStrength }))),
  protocol = { question:"Does per-lottery hierarchical time decay improve Global Win 6 versus frozen weekday frequency?", size:SIZE, candidates, weekdayLookback:12, allDaysLookback:84, minimumWeekdayDraws:4, minimumAllDaysDraws:28, minimumTrainingSources:10, minimumTargetOutcomes:10, split:"oldest 75% development selects one candidate; newest 25% holdout opened once", primary:"full pair covered on top2 or bottom2", bootstrap:{iterations:BOOTSTRAPS,cluster:"target date",seed:SEED}, productionChange:false },
  protocolHash = createHash("sha256").update(JSON.stringify(protocol)).digest("hex").slice(0,16);

type Candidate = (typeof candidates)[number];
type Row = { date:string; weekday:number; n:number; expected:number; baselineHits:number; candidateHits:Record<string,number>; topHits:Record<string,number>; bottomHits:Record<string,number>; bothHits:Record<string,number> };
nextEnv.loadEnvConfig(process.cwd());
const key = (candidate:Candidate) => `${candidate.halfLife}-${candidate.priorStrength}`,
  snapshots = await readAllSnapshots(),
  sources:GlobalWeekdaySource[] = Object.values(snapshots).map((snapshot)=>({lotteryId:snapshot.lotteryId,draws:getCanonicalDataset(snapshot,1000).analysisHistory.filter((draw)=>draw.top2&&draw.bottom2)})),
  dates=[...new Set(sources.flatMap((source)=>source.draws.map((draw)=>draw.drawDate)))].sort(), rows:Row[]=[];

for(const date of dates){
  const weekday=drawWeekday(date) as 0|1|2|3|4|5|6,
    targets=sources.flatMap((source)=>source.draws.filter((draw)=>draw.drawDate===date&&draw.top2&&draw.bottom2)),
    common={weekday,cutoffDate:date,weekdayLookback:12,allDaysLookback:84,minimumWeekdayDraws:4,minimumAllDaysDraws:28},
    trainingSources=eligibleGlobalWeekdaySources(sources,common).length,
    baseline=rankGlobalWeekdayMethod(sources,"weekday-frequency",common).slice(0,SIZE).map((item)=>item.digit);
  if(trainingSources<10||targets.length<10||baseline.length!==SIZE)continue;
  const candidateHits:Record<string,number>={},topHits:Record<string,number>={},bottomHits:Record<string,number>={},bothHits:Record<string,number>={};
  for(const candidate of candidates){const id=key(candidate),selected=rankTemporalShrinkage(sources,{...common,...candidate}).slice(0,SIZE).map((item)=>item.digit);candidateHits[id]=targets.filter((draw)=>pairCovered(selected,draw.top2!)||pairCovered(selected,draw.bottom2!)).length;topHits[id]=targets.filter((draw)=>pairCovered(selected,draw.top2!)).length;bottomHits[id]=targets.filter((draw)=>pairCovered(selected,draw.bottom2!)).length;bothHits[id]=targets.filter((draw)=>pairCovered(selected,draw.top2!)&&pairCovered(selected,draw.bottom2!)).length;}
  rows.push({date,weekday,n:targets.length,baselineHits:targets.filter((draw)=>pairCovered(baseline,draw.top2!)||pairCovered(baseline,draw.bottom2!)).length,expected:targets.reduce((sum,draw)=>sum+exactRandomPairCoverage(draw.top2!,SIZE)+exactRandomPairCoverage(draw.bottom2!,SIZE)-exactRandomBothCoverage(draw.top2!,draw.bottom2!,SIZE),0),candidateHits,topHits,bottomHits,bothHits});
}
if(rows.length<8)throw new Error(`Insufficient eligible dates: ${rows.length}`);
const split=Math.floor(rows.length*.75),development=rows.slice(0,split),holdout=rows.slice(split);
function summarize(sample:Row[],candidate:Candidate){const id=key(candidate),n=sample.reduce((sum,row)=>sum+row.n,0),hits=sample.reduce((sum,row)=>sum+row.candidateHits[id],0),baseline=sample.reduce((sum,row)=>sum+row.baselineHits,0),expected=sample.reduce((sum,row)=>sum+row.expected,0);return{dates:sample.length,outcomes:n,rate:hits/n,baselineRate:baseline/n,randomRate:expected/n,pairedVsBaseline:(hits-baseline)/n,upliftVsRandom:(hits-expected)/n,topRate:sample.reduce((sum,row)=>sum+row.topHits[id],0)/n,bottomRate:sample.reduce((sum,row)=>sum+row.bottomHits[id],0)/n,bothRate:sample.reduce((sum,row)=>sum+row.bothHits[id],0)/n};}
const devResults=candidates.map((candidate)=>({candidate,...summarize(development,candidate)})).sort((a,b)=>b.pairedVsBaseline-a.pairedVsBaseline||b.upliftVsRandom-a.upliftVsRandom||String(a.candidate.halfLife).localeCompare(String(b.candidate.halfLife))||a.candidate.priorStrength-b.candidate.priorStrength),selected=devResults[0];
function seeded(seed:number){let state=seed>>>0;return()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return(state>>>0)/4294967296}}
function interval(sample:Row[],candidate:Candidate,metric:"baseline"|"random",seed:number){const random=seeded(seed),values:number[]=[];for(let repeat=0;repeat<BOOTSTRAPS;repeat++){let numerator=0,denominator=0;for(let i=0;i<sample.length;i++){const row=sample[Math.floor(random()*sample.length)],id=key(candidate);numerator+=row.candidateHits[id]-(metric==="baseline"?row.baselineHits:row.expected);denominator+=row.n}values.push(denominator?numerator/denominator:0)}values.sort((a,b)=>a-b);return[values[Math.floor(BOOTSTRAPS*.025)],values[Math.floor(BOOTSTRAPS*.975)]] as const;}
const selectedCandidate=selected.candidate,developmentResult=summarize(development,selectedCandidate),holdoutResult=summarize(holdout,selectedCandidate),allResult=summarize(rows,selectedCandidate),holdoutBaselineCi=interval(holdout,selectedCandidate,"baseline",SEED+1),holdoutRandomCi=interval(holdout,selectedCandidate,"random",SEED+2),weekdayDiffs=Array.from({length:7},(_,weekday)=>{const sample=holdout.filter((row)=>row.weekday===weekday);return sample.length?{weekday,dates:sample.length,difference:summarize(sample,selectedCandidate).pairedVsBaseline}:null}).filter(Boolean) as {weekday:number;dates:number;difference:number}[],promotion=developmentResult.pairedVsBaseline>0&&holdoutBaselineCi[0]>0&&holdoutRandomCi[0]>0&&weekdayDiffs.filter((item)=>item.difference>0).length>=4&&Math.min(...weekdayDiffs.map((item)=>item.difference))>=-.03,
  historyHash=createHash("sha256").update(Object.values(snapshots).sort((a,b)=>a.lotteryId.localeCompare(b.lotteryId)).map((snapshot)=>`${snapshot.lotteryId}:${snapshot.historyVersion}`).join("|")).digest("hex").slice(0,16),pct=(value:number)=>`${(value*100).toFixed(2)}%`,pp=(value:number)=>`${value>=0?"+":""}${(value*100).toFixed(2)}pp`,ci=(value:readonly number[])=>`${pp(value[0])} to ${pp(value[1])}`,
  candidateRows=devResults.map((item)=>`| ${item.candidate.halfLife} | ${item.candidate.priorStrength} | ${pct(item.rate)} | ${pp(item.pairedVsBaseline)} | ${pp(item.upliftVsRandom)} |`).join("\n"),
  sectionRow=(label:string,value:ReturnType<typeof summarize>)=>`| ${label} | ${value.dates} | ${value.outcomes} | ${pct(value.rate)} | ${pct(value.baselineRate)} | ${pct(value.randomRate)} | ${pp(value.pairedVsBaseline)} | ${pp(value.upliftVsRandom)} | ${pct(value.topRate)} | ${pct(value.bottomRate)} | ${pct(value.bothRate)} |`,
  report=`# Global temporal shrinkage study\n\nFreeze date: ${FREEZE_DATE}  \nCode baseline: main@8a21e88  \nProtocol: \`${protocolHash}\`  \nHistory: \`${historyHash}\`\n\n## Pre-registered question\n\nCan a hierarchical, time-decayed per-lottery digit estimate improve Global Win 6 over frozen same-weekday frequency? This is a research-only model family. Production is not modified.\n\nEach lottery is normalized before equal-source aggregation. Recent same-weekday observations receive exponential decay, then shrink toward that lottery's prior 84-draw all-days rate. The target date and all future draws are excluded. Doubles count once per side. Available top/bottom sides receive equal weight.\n\nDevelopment evaluates the fixed 12-candidate grid below and selects exactly one candidate. Holdout is the newest 25% of dates and is used once for the final decision.\n\n## Development selection\n\n| Half-life | Prior strength | Either-side hit | vs Production | vs exact random |\n|---:|---:|---:|---:|---:|\n${candidateRows}\n\nSelected: **half-life ${selectedCandidate.halfLife}, prior strength ${selectedCandidate.priorStrength}**.\n\n## Final results\n\n| Section | Dates | Outcomes | Candidate | Production | Exact random | Candidate - Production | Candidate - random | Top | Bottom | Both |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n${sectionRow("Development",developmentResult)}\n${sectionRow("Holdout",holdoutResult)}\n${sectionRow("All descriptive",allResult)}\n\n- Holdout paired 95% CI vs Production: **${ci(holdoutBaselineCi)}**\n- Holdout uplift 95% CI vs exact random: **${ci(holdoutRandomCi)}**\n- Positive holdout weekdays: **${weekdayDiffs.filter((item)=>item.difference>0).length}/${weekdayDiffs.length}**\n- Worst holdout weekday: **${pp(Math.min(...weekdayDiffs.map((item)=>item.difference)))}**\n\n## Decision\n\n**${promotion?"RESEARCH_CANDIDATE_PASSES_FROZEN_GATE":"REJECT_NO_STABLE_HOLDOUT_EDGE"}**\n\nPassing would authorize a separate review only, never automatic production promotion. Development selection creates winner's-curse risk; holdout evidence must independently clear both comparison intervals and weekday consistency gates.\n\n## Contract confirmation\n\n- Production formula changed: **NO**\n- Production pool or eligibility changed: **NO**\n- Analyze UI changed: **NO**\n- Gemini contract changed: **NO**\n- Prospective tracking added: **NO**\n`;
await fs.mkdir(path.join(process.cwd(),"reports"),{recursive:true});await Promise.all([fs.writeFile(path.join(process.cwd(),"reports",`global-temporal-shrinkage-${FREEZE_DATE}.md`),report,"utf8"),fs.writeFile(path.join(process.cwd(),"reports",`global-temporal-shrinkage-${FREEZE_DATE}.json`),JSON.stringify({protocol,protocolHash,historyHash,data:{sources:sources.length,dates:rows.length,range:[rows[0].date,rows.at(-1)!.date],developmentDates:development.length,holdoutDates:holdout.length},developmentCandidates:devResults,selectedCandidate,results:{development:developmentResult,holdout:holdoutResult,all:allResult},confidence:{holdoutBaselineCi,holdoutRandomCi},weekdayDiffs,promotion},null,2),"utf8")]);
console.log(JSON.stringify({report:`reports/global-temporal-shrinkage-${FREEZE_DATE}.md`,protocolHash,historyHash,selectedCandidate,development:developmentResult,holdout:holdoutResult,confidence:{holdoutBaselineCi,holdoutRandomCi},weekdayDiffs,promotion},null,2));
